Add predelete step

diff --git a/bin/out b/bin/out
--- a/bin/out
+++ b/bin/out
@@ -76,12 +76,24 @@ echo "$pre_deploy_state"
 if [ "$exit_code" -eq 45 ]; then
     echo ""
     echo "Deleting previous stack that failed to create"
+    start_epoch="$(date +%s)"
     aws_with_retry --region "$region" cloudformation delete-stack --stack-name "${name}"
-    if [ "$?" -eq 0 ]; then
-        exit_code=25
-    else
-        echo ""
-        echo "Could not delete stack"
+    exit_code="$?"
+    if [ "$exit_code" -eq 0 ]; then
+        end_state="$(awaitComplete "$region" "$name")"
+        exit_code="$?"
+        if [ "$exit_code" -eq 0 ]; then
+            exit_code=25
+        fi
+        if [ "$exit_code" -ne 25 ]; then
+            echo "Failed to delete stack:"
+            echo ""
+            showErrors "$region" "$name" "$start_epoch"
+            echo ""
+            echo "FINAL STATE:"
+            echo ""
+            echo "$end_state"
+        fi
     fi
 fi
 
