Use aws command to check if updates will be made, this avoids complex logic to compare templates and parameters.

diff --git a/bin/out b/bin/out
--- a/bin/out
+++ b/bin/out
@@ -123,39 +123,44 @@ fi
 # execute
 #
 
-if ! cmp -s /tmp/stack-template-old.sorted /tmp/stack-template-new.sorted \
-|| ! cmp -s /tmp/stack-parameters-old /tmp/stack-parameters-new ; then
-  REM 'applying new stack configuration'
-  
-  aws cloudformation $STACK_ACTION \
-    $CAPABILITIES_ARG $PARAMETERS_ARG $TAGS_ARG \
-    --stack-name="$STACK_NAME" \
-    --template-body="file://$TEMPLATE" \
-    > /tmp/result
-  
-  REM 'waiting for completion'
-  
-  TIMED_OUT=true
-  
-  for s in $( seq 360 ) ; do
-    sleep 5
-    
-    load_stack
-    
-    if is_stack_completed ; then
-      TIMED_OUT=''
-      break
-    elif is_stack_errored ; then
-      fatal "$STACK_ACTION failed: $( jqstack '.Stacks[0].StackStatusReason' )"
-    fi
-  done
-  
-  if [ -n "$TIMED_OUT" ] ; then
-    fatal "$STACK_ACTION timed out"
-  fi
-  
-  REM 'completed'
+REM 'applying new stack configuration'
+
+aws cloudformation $STACK_ACTION \
+  $CAPABILITIES_ARG $PARAMETERS_ARG $TAGS_ARG \
+  --stack-name="$STACK_NAME" \
+  --template-body="file://$TEMPLATE" \
+  > /tmp/result 2> /tmp/aws-stderr || ret=$?
+
+MESSAGE="An error occurred (ValidationError) when calling the UpdateStack operation: No updates are to be performed."
+if [ $ret -eq 255 ] && [ "$(cat /tmp/aws-stderr | xargs)" == "$MESSAGE" ]; then
+  REM "No updates are to be performed"
+else
+  REM "An error occured: $(cat /tmp/aws-stderr)"
+  exit $ret
 fi
+
+REM 'waiting for completion'
+
+TIMED_OUT=true
+
+for s in $( seq 360 ) ; do
+  sleep 5
+  
+  load_stack
+  
+  if is_stack_completed ; then
+    TIMED_OUT=''
+    break
+  elif is_stack_errored ; then
+    fatal "$STACK_ACTION failed: $( jqstack '.Stacks[0].StackStatusReason' )"
+  fi
+done
+
+if [ -n "$TIMED_OUT" ] ; then
+  fatal "$STACK_ACTION timed out"
+fi
+
+REM 'completed'
 
 #
 # version
